services:
  extend-whitelist:
    image: extend-whitelist
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - 3000:3000
